/* Bilingual source dictionary. Text nodes keep their source across language changes. */
(function(root){
  'use strict';
  const pairs=[
    ['Katsele ympärillesi · Klikkaa käyttääksesi','Look around · Click to use'],
    ["Mene ulos","Go outside"],
    ["Keittiö","Kitchen"],
    ["Takka","Fireplace"],
    ["Nuku aamuun","Sleep until morning"],
    ["Säilytysarkku","Storage chest"],
    ["Juo mukista","Drink from the mug"],
    ["Täytä muki","Refill the mug"],
    ["Avaa / sulje ikkunaluukut","Open / close the shutters"],
    ["Sytytä / sammuta lyhty","Light / put out the lantern"],
    ["Olohuone · rauhallinen hetki","Living room · a quiet moment"],
    ["Klikkaa käyttääksesi","Click to use"],
    ["Sienilampi · Koti","Sienilampi · Home"],
    ["Aamun valo täyttää mökin. Kajo torkkuu vielä.","Morning light fills the cabin. Kajo is still dozing."],
    ["Muki on tyhjä. Täytä se vesitonkasta.","The mug is empty. Refill it from the water jug."],
    ["Virkistävä kulaus.","A refreshing drink."],
    ["Muki on täynnä.","The mug is full."],
    ["Rauhallinen hetki kotona. Nouse liikkumalla.","A quiet moment at home. Move to get up."],
    ["Kajo herättää sinut sängyn vierestä. Tarvitset ruokaa ja vettä.","Kajo wakes you by the bed. You need food and water."],
    ["Laita samanlainen työkalu ensin arkkuun, jotta sen kunto säilyy.","Store the matching tool first to preserve its condition."],
    ["Lepo palauttaa voimia ja terveyttä. Ruokaa, vettä ja polttopuuta kuluu yön aikana.","Rest restores energy and health. Food, water and firewood are still used overnight."],
    ["Kaikki","All"],
    ["Tyhjä","Empty"],
    ["Työkalujen kunto säilyy. Ota samanlaiset työkalut yksi kerrallaan.","Tool condition is preserved. Withdraw matching tools one at a time."],
    ["Lisää puuta ruoanlaittoon ja mökin lämmittämiseen. Savupiippu savuaa tulen palaessa.","Add wood to cook and warm the cabin. The chimney smokes while the fire burns."],
    ["Kypsennä","Cook"],
    ["Sammuta tuli","Put out the fire"],
    ["Sytytä tuli","Light the fire"],
    ["Mene ulos ennen matkustamista.","Go outside before travelling."],
    ["Rakenna ulkorakennelmat ulkona.","Build outdoor structures outside."],
    ["Juomapullo","Canteen"],
    ["Yksi juoma-annos. Täytä juomapaikalla. Tyhjä pullo on uudelleenkäytettävä.","One full drink. Refill at drinking spots. The empty bottle is reusable."],
    ["Juomapullo on tyhjä. Täytä se juomapaikalla.","The canteen is empty. Refill it at a drinking spot."],
    ["Pullo on nyt tyhjä. Säilytä se täyttämistä varten.","The canteen is empty now. Keep it to refill."],
    ["Juomapullo täytetty.","Canteen refilled."],
    ["Täysi · yksi annos","Full · one drink"],
    ["Tyhjä · täytä veden äärellä","Empty · refill at water"],
    ["Juo","Drink"],
    ["2 nahkaa","2 hides"],
    ["“Kaksi nahkaa kestävästä juomapullosta. Täytä se lähteellä, niin saat juotavaa matkalle. Nuoliakin löytyy. Mihinkään ei ole kiire.”","“Two hides for a sturdy canteen. Fill it at a spring and carry a drink for the trail. I have arrows too. Nothing here needs to be hurried.”"],
    ['Jätä lähteen ympärille tilaa. Rakenna hieman kauemmas.','Leave space around the spring. Build a little farther away.'],
    ['Pura','Dismantle'],['Puretaanko rakennelma?','Dismantle structure?'],['MATERIAALIT TALTEEN','RECOVER MATERIALS'],['Haluatko varmasti purkaa tämän rakennelman?','Are you sure you want to dismantle this structure?'],['Noin puolet rakennusmateriaaleista jää maahan. Parittomat määrät pyöristetään alaspäin. Lisättyä polttoainetta ei palauteta.','About half of its building materials will be left on the ground. Odd amounts are rounded down. Added fuel is not recovered.'],['Purettu. Kerää palautuneet materiaalit maasta.','Dismantled. Gather the recovered materials from the ground.'],['Hoida nuotiota','Tend the campfire'],['Lepää aamuun','Rest until morning'],['Tarkista ansa','Check the snare'],
    ['Astu mökkiin','Enter cabin'],['Klikkaa ovea','Click the door'],['Mökki on valmis. Sisätila lisätään myöhemmässä päivityksessä.','The cabin is ready. Its interior will be added in a later update.'],
    ['Minun täytyy syödä.','I need something to eat.'],['Tarvitsen vettä.','I need some water.'],['Olen aivan poikki. Kävelen hetken.','I am exhausted. I need to walk.'],['Minun täytyy päästä lämpimään.','I need to get warm.'],
    ['Piikiviveitsi','Flint knife'],['Retkikirves','Trail axe'],['Saarijousi','Ash bow'],['Pajuvapa','Willow rod'],['Nuoli','Arrow'],['Kuiva oksa','Dry branch'],['Jokikivi','River stone'],['Kasvikuitu','Plant fibre'],['Kuitunaru','Fibre cord'],['Variksenmarjat','Crowberries'],['Kangassieni','Edible mushroom'],['Tuore kala','Fresh fish'],['Loimukala','Cooked fish'],['Riistaliha','Raw game meat'],['Paistettu riista','Cooked game'],['Peurannahka','Hide'],['Messinkikompassi','Brass compass'],['Iso keppi','Large stick'],['Nuotiokehä','Fire ring'],['Laavusuoja','Lean-to'],['Neljä nuolta','Four arrows'],['Rihma-ansa','Snare'],['Metsäjänis','Hare'],['Teeri','Grouse'],['Metsäpeura','Deer'],['Karhu','Bear'],
    ['Terävä piikivi, puukahva ja varma ote. Tarvitaan tarkkoihin käsitöihin.','Sharp flint and a wooden handle. Needed for fine crafting.'],['Kevyt kirves kelopuiden pilkkomiseen. Varusta ennen puun hakkaamista.','A light axe for felling spruce and splitting trunks. Equip before chopping.'],['Hiljainen jousi metsälle. Varusta, tähtää hiirellä ja laukaise klikkaamalla.','A quiet hunting bow. Equip, aim with the mouse, and click to shoot.'],['Taipuisa vapa. Varusta ja klikkaa joen kalapaikkaa.','A flexible rod. Equip it and click a fishing spot.'],['Suora oksa ja piikivikärki. Yksi nuoli kuluu jokaisesta laukauksesta.','A straight shaft and flint tip. Each shot uses one arrow.'],['Metsän pohjalta kerättyä kuivaa puuta. Käsitöihin ja nuotion polttoaineeksi.','Dry fallen wood for crafting and campfire fuel.'],['Sileä harmaa kivi työkaluihin ja nuotiokehään.','A smooth grey stone for tools and fire rings.'],['Sitkeää luonnonkuitua. Kolmesta nipusta syntyy yksi naru.','Tough plant fibre. Three bundles make one cord.'],['Käsin kierrettyä narua. Sitoo kirveenterän, jousen ja laavun.','Hand-twisted cord for axes, bows, and shelters.'],['Kirpeä pieni välipala. Palauttaa ruokaa ja hieman nestettä.','A tart snack. Restores food and a little water.'],['Tunnistettu syötävä sieni. Pieni eväs matkalle.','An identified edible mushroom. A little food for the trail.'],['Kypsennä nuotiolla loimukalaksi.','Cook over a campfire before eating.'],['Lämmin, savuntuoksuinen ateria. Palauttaa ruokaa ja voimia.','A warm, smoky meal. Restores food and energy.'],['Kypsennä nuotiolla ennen syömistä.','Cook over a campfire before eating.'],['Tukeva metsäretkeilijän ateria.','A hearty meal for a woodland traveller.'],['Pehmeä nahka. Aarni vaihtaa sen mielellään tarvikkeisiin.','A soft hide. Aarni will exchange it for supplies.'],['Aarnin vanha kompassi. Muisto ensimmäisestä vaihtokaupasta.','Aarni’s old compass. A keepsake from your first trade.'],
    ['Suomalainen hiiliteräspuukko visakoivukahvalla. Riistan nylkemiseen.','A Finnish carbon-steel knife with a curly-birch handle. Skin hunted game and prepare kindling.'],['Rungosta pilkottu tukeva keppi. Pitkään palavaa nuotiopuuta.','A stout billet split from a fallen trunk. Excellent slow-burning campfire fuel.'],
    ['Ensimmäinen työkalu. Avaa kirveen, jousen ja vavan valmistuksen.','Your first crafted tool. Unlocks axes, bows, and rods.'],['Kierrä kolme kuitunippua yhdeksi kestäväksi naruksi.','Twist three fibre bundles into a strong cord.'],['Valmista ensin veitsi ja naru. Kirveellä saat kelopuusta kuusi puuta.','Make a flint knife and cord first. Fell a tree, collect its branches, then split its trunks.'],['Rakenna jalkojesi viereen. Lämmittää ja kypsentää ruokaa.','Build beside the trail. Add wood to warm yourself and cook.'],['Oma lepopaikka. Nuku aamuun ja palauta voimasi.','A place to rest. Sleep until morning and recover your energy.'],['Lähesty riistaa kyykyssä. Muista valmistaa myös nuolia.','Approach game while crouching. Remember to craft arrows.'],['Neljä nuolta saarijouseen.','Four arrows for your ash bow.'],['Vapa veden äärelle. Nosta kala, kun koho nykäisee.','Cast beside water. Reel in when the float dips.'],['Aseta polun reunaan. Tarkista minuutin kuluttua.','Place beside the trail. Check in about a minute.'],
    ['Kerää oksia, kiviä ja kuitua','Gather branches, stones, and fibre'],['Valmista piikiviveitsi','Craft a flint knife'],['Valmista retkikirves','Craft a trail axe'],['Valmista piikivikirves','Craft a flint axe'],['Rakenna nuotio','Build a campfire'],['Rakenna laavu','Build a lean-to'],['Juo lähteestä','Drink fresh water'],['Tapaa erakko Aarni','Meet Aarni'],['Tee vaihtokauppa','Trade with Aarni'],['Valmista lämmin ateria','Cook a warm meal'],
    ['Tämä esine täytyy ensin valmistaa tai kerätä.','Craft or gather this item first.'],['Olet jo kylläinen ja levännyt.','You are already well fed and rested.'],['Kerää ensin reseptissä näkyvät puuttuvat tarvikkeet.','Gather the missing recipe ingredients first.'],['Siirry hieman kauemmas olemassa olevasta leiristä.','Move a little further from the existing camp.'],['Kajo lähtee kepin perään.','Kajo bounds after the stick.'],['Heräät uuteen aamuun. Kajo venyttelee vieressä.','You wake to a new morning. Kajo stretches beside you.'],['Ansa on viritetty. Tarkista vähän myöhemmin.','The snare is set. Check again later.'],['Ansassa on riistaa.','There is game in the snare.'],['Raikas lähdevesi sammuttaa janon.','Fresh water quenches your thirst.'],['Mene ensin palavan nuotion äärelle.','Approach a burning campfire first.'],['Ateria on valmis. Löydät sen repusta ja ylävalikosta.','Your meal is ready in the backpack and top belt.'],['Aarni pyytää yhden nahan tai kaksi loimukalaa.','Aarni asks for one hide or two cooked fish.'],['Sait kalan! Kypsennä se nuotiolla.','A fish! Cook it over a campfire.'],['Kala pääsi karkuun. Odota, kunnes koho nykäisee.','The fish escaped. Wait for the float to dip.'],['Nuolet loppuivat. Valmista lisää käsitöissä.','Out of arrows. Make more in Crafting.'],['Kajo johdattaa sinut takaisin leiripaikalle. Lepää ja syö.','Kajo leads you back to camp. Rest and eat.'],['Kala nykäisi ja katosi. Kokeile uudestaan.','The fish nibbled and vanished. Try again.'],['Palaat metsän leiripaikalle.','You return to the forest camp.'],['Heitä siima','Cast your line'],['Kajo · heitä keppi','Kajo · throw a stick'],['Nuotio · valmista ruokaa','Campfire · fuel and cook'],['Vanha nuotiokehä','Old fire ring'],['Laavu · lepää aamuun','Lean-to · sleep until morning'],['Tarkista ansa','Check the snare'],['Kerää · ','Gather · '],[' — lähesty kyykyssä.',' — approach while crouching.'],[' syöty.',' eaten.'],[' valmistui.',' crafted.'],
    ['Viimeistele nykyinen toiminto ensin.','Finish the current action first.'],['Ota kirves käteen ylävalikosta tai repusta.','Equip your axe from the top belt or backpack.'],['Ota puukko käteen nylkeäksesi eläimen.','Equip your puukko to skin this animal.'],['Nuotiossa on jo riittävästi puuta.','The fire already has plenty of fuel.'],['Aarni pyytää vaihdossa viisi oksaa.','Aarni needs five branches for this trade.'],['Aarni pyytää yhden nahan.','Aarni asks for one hide.'],['Vaihtokauppa tehty. Tarvikkeet ovat repussasi.','Trade complete. Your supplies are in the backpack.'],['Nuotio sammui. Lisää kuivaa puuta sytyttääksesi sen.','The campfire has gone out. Add dry wood to relight it.'],['Riista kaatui. Lähesty puukko kädessä saadaksesi lihan ja nahan.','Game down. Approach with your puukko to recover meat and hide.'],['Nyljetty ja pakattu. Kypsennä liha nuotiolla.','Skinned and packed. Cook the meat at a campfire.'],['Kuusi · kaada kirveellä','Spruce · fell with axe'],['Rankapuu · pilko kirveellä','Trunk · split with axe'],['Riista · nylje puukolla','Game · skin with puukko'],['Aarnin mökki · koputa oveen','Aarni’s cabin · knock on the door'],[' · klikkaa lähestyäksesi',' · click to approach'],
    ['Selain ei sallinut tallennusta. Retki jatkuu, mutta edistyminen ei säily sulkemisen jälkeen.','Saving is unavailable in this browser. You can play, but progress will not survive closing.'],['Tervetuloa takaisin metsään.','Welcome back to the woods.'],['Aloita läheltä: klikkaa polun oksia, kiviä ja kuitunippuja.','Start nearby: click branches, stones, and fibre along the trail.'],['Hiljaa aluskasvillisuudessa','Moving quietly'],['Hiljainen vaeltaja','The quiet traveller'],['Vapaat kädet','Empty hands'],['W / ↑ nouse seisomaan','W / ↑ stand up'],['Yläreunasta työkalut ja eväät','Move to the top edge for tools and food'],['Yläreunasta pikavalinnat','Top edge for quick slots'],['Leirisi on valmis. Kulje omaa polkuasi.','Your camp is ready. Follow your own trail.'],[' nuolta',' arrows'],[' · ei repussa',' · not in backpack'],[' · klikkaa pois käytöstä',' · click to unequip'],[' · syö',' · eat'],[' · varusta',' · equip'],['Koho nykäisi — nosta nyt!','The float dipped — reel in!'],['Hiljaa… odota kohon nykäisyä.','Quietly… wait for the float to dip.'],['Nosta kala!','Reel in!'],['Nosta vapa','Lift the rod'],['Siima on vedessä…','Your line is in the water…'],
    ['KAIKKI TARPEELLINEN MUKANA','EVERYTHING YOU NEED'],['OMIN KÄSIN · LUONNON ANTIMISTA','BY HAND · FROM THE FOREST'],['YHDEN POLUN ALKU','THE BEGINNING OF A TRAIL'],['PIENIÄ HETKIÄ METSÄSTÄ','MOMENTS IN THE WOODS'],['KULJE OMAAN TAHTIISI','WALK AT YOUR OWN PACE'],['LÄMPÖÄ JA LÄMMIN ATERIA','WARMTH AND A HOT MEAL'],['NYKYINEN RETKI ON TALLENNETTU','YOUR CURRENT JOURNEY IS SAVED'],['Uusi retki?','A new journey?'],['Retkeilijän opas','Field guide'],['Kenttäpäiväkirja','Field journal'],['Nuotion äärellä','At the campfire'],['Käsityöt','Crafting'],['Reppu','Backpack'],['Kaikki','All'],['Työkalut','Tools'],['Eväät','Food'],['Tarvikkeet','Materials'],['KYPSENNETTÄVÄ','COOK BEFORE EATING'],['TYÖKALU','TOOL'],['TARVIKE','MATERIAL'],['EVÄS','FOOD'],[' kappaletta',' items'],['Repussa ','In your pack: '],[' kpl',' items'],[' · Käytössä',' · Equipped'],['Syö eväs','Eat'],['Pois kädestä','Unequip'],['Ota käyttöön','Equip'],['Kypsennä palavan nuotion äärellä.','Cook at a burning campfire.'],['Avaa käsityöt →','Open crafting →'],['Tässä taskussa ei vielä ole mitään. Kerää polulta tarvikkeita hiirellä.','This pocket is empty. Click resources along the trail to gather them.'],['Tarvikkeet valmiina','Ready to craft'],['Katso tarvikkeet','View ingredients'],['LEIRIN RAKENTAMINEN','CAMP BUILDING'],['KÄSIN VALMISTETTU','HANDCRAFTED'],['Työkaluksi tarvitaan ','Required tool: '],['Työkalu ei kulu valmistuksessa.','The tool is not consumed.'],['Katso sen resepti →','View its recipe →'],['Valmistuu paljain käsin. Et tarvitse muita työkaluja.','Made by hand. No other tools required.'],['Rakenna tähän','Build here'],['Tarvikkeita puuttuu','Missing ingredients'],['Valmista','Craft'],
    ['Retken muistilista','Trail checklist'],['Metsän asukkaat','Forest dwellers'],['Tuntematon jälki','Unknown tracks'],['Saaliiksi saatu','Hunted'],['Havaittu','Observed'],['Kyykisty S- tai ↓-näppäimellä. Riista huomaa sinut silloin vasta paljon lähempää.','Crouch with S or ↓ to approach wildlife more closely.'],['Kajo antaa sinun kulkea edellä. Jos hän jää jälkeen, hän ottaa sinut kyllä kiinni.','Kajo lets you lead. If he lingers, he will catch up.'],['Tallenna retki nyt →','Save journey now →'],['Retki tallennettu.','Journey saved.'],['Metsän äänet päällä.','Forest sounds on.'],['Äänet mykistetty.','Sound muted.'],['Selain ei sallinut koko näytön tilaa.','Fullscreen is unavailable in this browser.'],['Uusi retki korvaa tämän selaimen nykyisen tallennuksen. Vanhan peliversion alkuperäinen tallennus säilyy erikseen.','A new journey replaces the current save in this browser. The original older-version save is kept separately.'],['Aloita uusi retki','Start a new journey'],['Aloita retki','Begin your journey'],['Jatka retkeä','Continue journey'],['Peruuta','Cancel'],['Keskeytä','Cancel'],['Valmistellaan metsää…','Preparing the forest…'],['Metsäkuvaa ei voitu ladata. Tarkista, että assets-kansio on index.html-tiedoston vieressä.','The forest image could not load. Keep the assets folder beside index.html.'],['Lataus epäonnistui','Loading failed'],
    ['A / D tai ← / →','A / D or ← / →'],['Kulje polkua. Shift-näppäimellä juokset.','Walk the trail. Hold Shift to run.'],['Kyykisty ja nouse. Kyykyssä liikut hiljaisemmin ja pääset lähemmäs riistaa.','Crouch and stand up. Crouching is quieter and lets you approach wildlife.'],['Hiiren klikkaus','Mouse click'],['Kerää korostettu kohde, juo vettä, käytä leiriä tai heitä Kajolle keppi. Kävele ensin lähelle.','Click a highlighted object to walk over and gather it, drink, use camp, or throw a stick for Kajo.'],['Työkalut ja eväät tulevat näkyviin. Klikkaa työkalua uudestaan ottaaksesi sen pois kädestä.','Tools and food appear. Click an equipped tool again to put it away.'],['Reppu, käsityöt, kartta, päiväkirja ja äänten kytkin.','Backpack, crafting, map, journal, settings, and sound.'],['Kirveen valmistus','Crafting an axe'],['Tee veitsi (2 kiveä + oksa) ja naru (3 kuitua). Tee sitten kirves (2 kiveä + 3 oksaa + naru).','Make a flint knife (2 stones + a branch) and cord (3 fibre). Then an axe (2 stones + 3 branches + cord).'],['Jousi ja vapa','Bow and rod'],['Jousella tähtää ja ammu hiirellä. Vavalla klikkaa vettä, odota kohon nykäisyä ja nosta kala.','Aim and shoot with the mouse. With a rod, click water, wait for a bite, then reel in.'],['Peli tallentaa automaattisesti selaimeen. Valikot ja piilotettu välilehti pysäyttävät peliajan. Metsästä polku jatkuu Aarnijoelle ja Sienilammelle.','Progress saves automatically in this browser. Menus and hidden tabs pause time. The forest trail continues to Aarni River and Sienilampi.'],['Yläreuna','Top edge'],['Oikea reuna','Right edge'],
    ['Polku katoaa metsään.','The trail disappears into the trees.'],['Sinulla ei ole kiire minnekään.','There is nowhere you need to hurry.'],['H I L J A I N E N   K O R P I','THE QUIET NORTH'],['OMA POLKUSI · OMA TAHTISI','YOUR TRAIL · YOUR PACE'],['Itsenäinen eräretkiprototyyppi','An independent wilderness prototype'],['RETKEN MUISTILISTA','TRAIL CHECKLIST'],['Avaa kenttäpäiväkirja','Open field journal'],['K O R P I L A A K S O','THE NORTHERN VALLEY'],['Metsä','Forest'],['PÄIVÄ','DAY'],['TYYNI','CALM'],['SADE','RAIN'],['YÖ','NIGHT'],['RUOKA','FOOD'],['VESI','WATER'],['VOIMA','ENERGY'],['LÄMPÖ','WARMTH'],['Hahmon vointi','Traveller condition'],['Työkalujen ja eväiden pikavalinnat','Quick tools and food'],['RETKIVYÖ','FIELD BELT'],['Retkityökalut','Field tools'],['Avaa reppu','Open backpack'],['Avaa käsityöt','Open crafting'],['Avaa kartta','Open map'],['Avaa päiväkirja','Open journal'],['TARVIKKEET & EVÄÄT','SUPPLIES & FOOD'],['VALMISTA & RAKENNA','CRAFT & BUILD'],['VALITSE ALUE','CHOOSE A REGION'],['HAVAINNOT & TEHTÄVÄT','OBSERVATIONS & TASKS'],['Päiväkirja','Journal'],['Kartta','Map'],['Ohjeet','Help'],['Kenttäopas','Field guide'],['Äänet päälle tai pois','Toggle sound'],['Äänet','Sound'],['Koko näyttö','Fullscreen'],['Piilota ohjevihje','Dismiss hint'],['Sulje näkymä','Close window'],['Metsä odottaa. Aika pysähtyy valikoissa.','The forest waits. Menus pause time.'],['Peli tarvitsee JavaScriptin toimiakseen.','This game requires JavaScript.'],[' liiku',' move'],[' kyykisty',' crouch'],['♧ klikkaa ja kerää','♧ click to gather'],
    ['Asetukset','Settings'],['OLE KUIN KOTONASI','MAKE YOURSELF AT HOME'],['Tutulla kielellä metsäpolulle','A familiar voice on the trail'],['Kielivalinta tallennetaan tälle laitteelle. Retkesi jatkuu ennallaan.','Your language choice is saved on this device. Your journey is unchanged.'],['Äänet voi mykistää retkivyön ♪-painikkeesta.','Sound can be muted from the ♪ button on the field belt.'],['Suomi','Finnish'],['Englanti','English'],['LÄMMIN LIESI · TUTUT KASVOT','A WARM HEARTH · A FAMILIAR FACE'],['Aarnin pöydän ääressä','Aarni’s table'],['REILU VAIHTOKAUPPA','A FAIR EXCHANGE'],['Pohjoiset polut','The northern trails'],['KARTTA TULEVASTA','A MAP OF THINGS TO COME'],['POHJOISET POLUT','THE NORTHERN TRAILS'],['Syvä metsä','Deep woods'],['Palanut metsä','Burnt forest'],['Joen ranta','Riverbank'],['Vaara','Fell'],['Vuori','Mountain'],['NYKYINEN ALUE','CURRENT REGION'],['TUTKIMATTA','UNEXPLORED'],['Vanha mökki','Old cabin'],['Harjumökki','Ridge cabin'],['Tuleva turvatalo · Kunnosta tämä mökki','Future safe house · Restore this cabin'],['Harmaat paikat avautuvat myöhemmässä luvussa.','Grey locations will open in a future chapter.'],['Sammaleisia runkoja, kirkasta vettä ja hiljaisia polkuja.','Mossy timber, clear water, and quiet trails.'],['Palaa leiripaikalle','Return to camp'],
    ['Tasainen lämpö','A steady warmth'],['Kylmä hiillos','Cold embers'],['Polttoainetta jäljellä (peliaikaa)','Fuel remaining (game time)'],['Lisää kuivia oksia tai pilkottuja keppejä. Nuotio sammuu polttoaineen loputtua. Aika pysähtyy tässä ikkunassa.','Add dry branches or split billets. The fire dies when its fuel runs out. Time pauses while this window is open.'],['Seiso nuotion lähellä lämmitelläksesi.','Stand near the fire to warm up.'],['Lisää puita ennen ruoanlaittoa.','Add fuel before cooking.'],['Lisää ','Add '],['Kompassi + 8 nuolta','Compass + 8 arrows'],['8 nuolta','8 arrows'],['1 nahka TAI 2 kypsää kalaa','1 hide OR 2 cooked fish'],['5 kuivaa oksaa','5 dry branches'],['Visakoivukahvainen puukko','Birch-handled puukko'],['1 nahka','1 hide'],['Repussasi: ','In your pack: '],['← Takaisin keskusteluun','← Back to conversation'],['“Reilu vaihto. Ota mitä tarvitset matkallesi.”','“A fair exchange. Take what you need for the trail.”'],
    ['· Mökin isäntä','· The cabin keeper'],['Tule sisään. Varo lastuja.','Come in. Mind the shavings.'],['Vanha mies kääntää keskeneräistä kuksaa käsissään. Kahvi höyryää puukon vieressä. ”Aarni. Tätä liettä on tullut lämmitettyä kauemmin kuin jaksan laskea. Mikä sinut toi polulleni?”','The old man turns a half-carved kuksa in his hands. Coffee steams beside the knife. “Aarni. Been keeping this stove warm longer than I care to count. What brings you along my trail?”'],['Etsin sopivaa leiripaikkaa.','I am looking for a place to make camp.'],['Onpa kaunis kuksa.','That is a beautiful kuksa.'],['Pieni suoja kantaa pitkälle.','A little shelter goes a long way.'],['”Kuiva maa, katto ja tarpeeksi pilkottua puuta yöksi. Siitä on hyvä aloittaa. Syrjemmän vanhat mökitkin kaipaisivat vielä ahkeria käsiä.”','“Dry ground, a roof, and enough split wood for the night. That is a good beginning. The old cabins further out could use a pair of willing hands, one day.”'],['Voisimmeko vaihtaa tarvikkeita?','Could we exchange a few supplies?'],['Teetkö kaiken itse?','Do you make everything yourself?'],['Koivu muistaa kätesi muodon.','Birch remembers the shape of your hand.'],['”Hidasta työtä. Terävä puukko ja vähän kärsivällisyyttä. Tämä tulee ystävälle.” Hän pyyhkäisee lastun pöydältä. ”Pidä omakin teräsi kunnossa. Riistan käsittelyssä sitä tarvitsee.”','“Slow work. A sharp puukko, a little patience. This one is for a friend.” He brushes a curl of wood from the table. “Keep your own blade sharp. You will need it to dress game.”'],['Mitä tarvikkeita sinulla on?','What supplies do you have?'],['Mitä minun pitäisi tietää tästä metsästä?','What should I know about this forest?'],['Voimme auttaa toisiamme.','We can help each other along.'],['”Hyvä nahka tai pari kypsää kalaa varakompassistani. Nuoliakin löytyy. Ei tässä kiirettä pidetä.”','“A good hide or a couple of cooked fish for my spare compass. I have arrows too. Nothing here needs to be hurried.”'],['Katsotaan vaihtokauppoja.','Let us see what we can trade.'],['Pannu on yhä lämmin.','The kettle is still warm.'],['”Kuulin teeren puron takana aamulla. Vain yhden.” Aarni laskee veistoksen pöydälle. ”Miten leirisi rakentaminen sujuu?”','“Heard a grouse beyond the stream this morning. Just the one.” Aarni sets his carving down. “How is your camp coming along?”'],['”Satoi tai paistoi, aina löytyy vähän pilkottavaa.” Aarni hymyilee kahvinsa takaa. ”Tarvitsetko jotain matkallesi?”','“Rain or shine, there is always a little wood to split.” Aarni smiles over his coffee. “Need anything for the trail?”'],['Tehdään vaihtokauppaa.','Let us trade.'],['Miten kuksa edistyy?','How is the carving coming along?'],['Aarni veistää kuksaa mökkinsä pöydän ääressä, höyryävä kahvikuppi vierellään.','Aarni carving a kuksa at his cabin table, beside a steaming coffee cup.'],['Aarnin hirsimökki','Aarni’s log cabin']
  ];
  pairs.push(['Metsä · palaat vanhalle nuotiopaikalle.','Forest · you return to the old campfire.'],['Sytykkeet','Kindling'],['Vuole yksi iso keppi kolmeksi pieneksi oksaksi käsitöihin tai nuotion sytyttämiseen.','Shave one split billet into three small branches for crafting or lighting a fire.'],['Metsä. Liiku A- ja D-näppäimillä, kyykisty S-näppäimellä ja kerää hiirellä.','Forest. Move with A and D, crouch with S, and gather with the mouse.']);
  pairs.push(['Undiscovered recipe','Tuntematon resepti'],['Unknown wildlife entry','Tuntematon eläinhavainto'],['METSÄN ASUKKAAT','FOREST DWELLERS'],['Hiljainen kulkija näkee enemmän. Lähesty riistaa kyykyssä ja anna metsän kertoa nimensä omassa tahdissaan.','A quiet traveller sees more. Approach wildlife while crouching and let the forest reveal each name in its own time.'],[' havaittu',' observed'],['TUNTEMATON KÄSITYÖ','UNDISCOVERED CRAFT'],['Kerää ja tunnista tarvikkeita','Gather and identify materials'],['Uudet reseptit piirtyvät tähän, kun olet löytänyt niiden tarvitsemat tarviketyypit.','New recipes will appear here when you have discovered the material types they require.']);
  pairs.push(['Demon sisältö loppuu tähän. Lisää polkuja avautuu myöhemmässä luvussa.','The demo ends here. More trails will open in a future chapter.']);
  pairs.push(
    ['Piikivikirves','Flint axe'],['Teräskirves','Steel axe'],['Alkukantainen kivikirves. Hidas, mutta sillä kaataa kuusen ja pilkkoo rungon.','A primitive stone axe. Slow, but able to fell spruce and split trunks.'],['Aarnin teräskirves. Nopeampi ja kestävämpi kuin piikivikirves.','Aarni’s steel axe. Faster and more durable than a flint axe.'],['Valmista ensin piikiviveitsi ja naru. Hidas kivikirves kaataa puun ja pilkkoo rankapuut.','First make a flint knife and cord. The slow stone axe can fell trees and split trunks.'],
    ['Suomalainen hiiliteräspuukko visakoivukahvalla. Nylkee riistan nopeammin ja kestää piikiviveistä pidempään.','A Finnish carbon-steel knife with a curly-birch handle. Skins game faster and outlasts a flint knife.'],['Terävä piikivi, puukahva ja varma ote. Tarvitaan tarkkoihin käsitöihin ja riistan nylkemiseen.','Sharp flint, a wooden handle, and a sure grip. Needed for fine crafting and skinning game.'],
    ['Ota piikivikirves tai teräskirves käteen ylävalikosta tai repusta.','Equip a flint axe or steel axe from the top belt or backpack.'],[' hajosi kovassa käytössä.',' broke after hard use.'],['Aarni pyytää teräskirveestä kaksi nahkaa.','Aarni asks for two hides for the steel axe.'],
    ['Tämä työkalu on loppuun kulunut. Valmista tai vaihda tilalle uusi.','This tool is worn out. Craft or trade for a replacement.'],['Kuusi · kaada kirveellä','Spruce · fell with an axe'],['Rankapuu · pilko kirveellä','Trunk · split with an axe'],['Riista · nylje veitsellä','Game · skin with a knife'],['Ota piikiviveitsi tai puukko käteen nylkeäksesi eläimen.','Equip a flint knife or puukko to skin this animal.'],['Riista kaatui. Lähesty piikiviveitsi tai puukko kädessä saadaksesi lihan ja nahan.','Game down. Approach with a flint knife or puukko to recover meat and hide.'],
    ['Kenttämuistiinpanot','Field Notes'],['Päiväkirjan osiot','Journal sections'],['Päävalikko','Main menu'],['Avaa päävalikko','Open main menu'],['RETKESI ON TURVASSA','YOUR JOURNEY IS SAFE'],['Jatka retkeä','Resume journey'],['Mykistä tai palauta metsän äänet','Mute or restore forest sounds'],['Palaa aloitusvalikkoon','Return to title menu'],['Retkesi tallennetaan ennen aloitusvalikkoon palaamista.','Your journey is saved before returning to the title menu.'],['Takaisin päävalikkoon','Back to main menu'],
    ['Työkalut, yksi valitsemasi pikaeväs ja päiväkirja tulevat näkyviin.','Tools, your chosen quick food, and the journal appear.'],['Reppu, käsityöt, kenttämuistiinpanot ja kartta ovat saman kirjan välilehdillä. Vedä eväs repusta pikaeväspaikkaan tai valitse se painikkeella.','Backpack, Crafting, Field Notes, and Map share one journal. Drag food from the backpack to the quick slot, or assign it with the button.'],['Piikivikirves','Flint axe'],['Tee piikiviveitsi ja naru, sitten piikivikirves. Aarnilta voit myöhemmin vaihtaa kestävämmän teräskirveen.','Make a flint knife and cord, then a flint axe. Later, Aarni can trade you a sturdier steel axe.'],
    ['PIKAEVÄS','QUICK FOOD'],['Pikaeväs: ','Quick food: '],['. Pudota eväs tähän tai valitse eväs repusta.','. Drop food here or choose food from the backpack.'],['Kunto ','Condition '],['Valittu pikaevääksi','Assigned to quick food'],['Aseta pikaevääksi','Assign to quick food'],['Pikaeväs vaihdettu.','Quick food changed.'],['Sopiva työkalu: ','Suitable tool: '],
    ['Vaihda metsän äänet päälle tai pois','Toggle forest sounds'],['Sulje asetukset','Close settings'],['Teräksinen retkikirves','Steel trail axe'],['2 nahkaa','2 hides'],['Työkalukuvia ei voitu ladata assets-kansiosta.','Tool images could not be loaded from the assets folder.']
  );
  pairs.push(['MATKA','JOURNEY'],['Aloita alusta','Start from the beginning'],['Nollaa nykyinen retkesi. Kielivalintasi säilyy, ja vanhat perintötallennukset pysyvät koskemattomina.','Reset your current journey. Your language preference is kept, and older legacy saves remain untouched.'],['Nollaa nykyinen retki','Reset current journey']);
  pairs.push(['Valmista ensin piikiviveitsi ja naru. Kaada puu, kerää oksat ja pilko rankapuut.','Make a flint knife and cord first. Fell a tree, collect its branches, then split its trunks.'],['Klikkaa korostettua kohdetta: hahmo kävelee viereen ja kerää. Voit myös juoda, käyttää leiriä tai heittää Kajolle kepin.','Click a highlighted object to walk over and gather it, drink, use camp, or throw a stick for Kajo.']);
  pairs.push(['Aseta pikapaikkaan','Assign to belt slot'],['Vedä puukko, kirves tai eväs yläpalkin vastaavaan paikkaan.','Drag a knife, axe, or food to its matching slot in the top belt.'],['Journal-kuvia ei voitu ladata.','Journal images could not be loaded.']);
  pairs.push(['Metsä ja toiminnot','Forest & actions'],['Musiikki','Music'],['Päällä','On'],['Pois','Off'],['Korkea vuoristo','High mountains'],['Talviset vaarat','Winter fells'],['Avoin tasanko','Open plains'],['SEURAAVA LUKU','NEXT CHAPTER'],['Vanha jokimökki · tuleva kunnostusprojekti','Old riverside cabin · future restoration project'],['Metsä · nykyinen polkusi. Jokiranta ja sen vanha mökki ovat seuraava luku.','Forest · your current trail. The riverbank and its old cabin are the next chapter.'],['Jokiranta · seuraava luku. Kunnosta vanha jokimökki. Alue ei ole vielä pelattavissa.','Riverbank · next chapter. Restore the old riverside cabin here. This area is not playable yet.'],['Korkea vuoristo · vaativa tuleva loppupelialue.','High mountains · a demanding future endgame region.'],['Talviset vaarat · luminen metsä, kylmät tuulet ja tulevat polut.','Winter fells · snowy woodland, cold winds and future trails.'],['Avoin tasanko · tulevat metsästysmaat ja harvinainen riista.','Open plains · future hunting grounds and rare wildlife.'],['Käsin piirretty kartta metsistä, keskellä kulkevasta joesta, lumisista vaaroista, vuorista ja tasangoista.','Hand-drawn map of forests, a central river, snowy fells, high mountains and open plains.']);
  pairs.push(['Rapsuta Kajoa','Pet Kajo'],['Heitä keppi','Throw a stick'],['Nouda lintu','Retrieve the bird'],['Valitse rullalla · Vahvista klikkaamalla','Wheel to choose · Click to confirm'],['Kajo painautuu kättäsi vasten.','Kajo leans into your hand.'],['Kajo on varattu. Odota hetki.','Kajo is busy. Give him a moment.'],['Lähellä ei ole kaadettua lintua.','There is no downed bird nearby.'],['Kajo lähtee noutamaan lintua.','Kajo goes to retrieve the bird.'],['Kajo tuo linnun. Nylje se puukolla.','Kajo brings the bird. Skin it with a knife.'],['S / W / ↑ nouse seisomaan','S / W / ↑ stand up'],['Tab avaa tai sulkee päiväkirjan. S vaihtaa kyykyn ja seisomisen välillä; W nostaa seisomaan. Koiran päällä rulla valitsee toiminnon ja klikkaus vahvistaa.','Tab opens or closes Journal. S toggles crouching; W stands up. Hover Kajo, use the wheel to choose an action, then click to confirm.']);
  for(const [fi,en]of pairs.slice(0,19))pairs.push([fi.toLowerCase(),en.toLowerCase()]);
  pairs.push(['Rakenna kuivalle maalle, pois laiturilta.','Build on dry ground, away from the jetty.']);
  pairs.push(['SEURAAVA POLKU','THE NEXT TRAIL'],['Matkustetaanko tälle alueelle?','Travel to this region?'],['Matkusta','Travel']);
  pairs.push(['Klikkaa ja istu · Liiku noustaksesi','Click to sit · Move to stand']);
  pairs.push(['Kuusi','Spruce'],['Kaadettu ranka','Fallen trunk'],['Kaadettu riista','Downed game'],['Klikkaa ja kaada · kirves','Click to fell · axe'],['Klikkaa ja pilko · kirves','Click to split · axe'],['Klikkaa ja nylje · veitsi','Click to skin · knife'],['Klikkaa ja kerää','Click to gather'],['VIERAILTU','VISITED']);
  pairs.push(['Aarnijoen polku','Aarni River Trail'],['Vanha metsäpolku ja Aarnin mökki.','The old forest trail and Aarni’s cabin.'],['Seuraa metsäpolkua joelle. Hiljainen sivupolku vie Sienilammelle.','Follow the forest path to the river. A quiet trail branches toward Sienilampi.'],['Unohdettu rantamökki, vanha laituri ja tyyni vesi.','A forgotten lakeside cabin, a weathered jetty, and still water.'],['AVOIN POLKU','OPEN TRAIL'],['TERVEYS','HEALTH'],['Tyhjät perustarpeet kuluttavat terveyttä','Empty needs drain health'],['Terveys vähissä — lepää ja toivu','Low health — rest and recover'],['Lyyhistyit. Kajo toi sinut turvaan. Lepää, syö ja juo.','You collapsed. Kajo brought you back to safety. Rest, eat and drink.'],['Mökkilähde','Cabin spring'],['Klikkaa ja juo','Click to drink'],['Julkisivu','Facade'],['Katto','Roof'],['Hirsiseinät','Log walls'],['Piha','Yard'],['Ovi','Door'],['Ikkunat','Windows'],[' · Kunnostettu',' · Restored'],[' · Kunnosta',' · Restore'],['Sienilampi · mökin kunnostus','Sienilampi · cabin restoration'],['Istu veden äärelle','Sit by the water'],['Hiljainen hetki Sienilammella. Liiku noustaksesi.','A quiet moment by Sienilampi. Move to stand up.'],['Tämä mökin osa on jo kunnostettu.','This part of the cabin is already restored.'],['Kerää mökin osan yläpuolella näkyvät tarvikkeet.','Gather the materials shown above this part of the cabin.'],['Sienilammen kalastus tulee myöhemmin. Nauti toistaiseksi veden rauhasta.','Fishing at Sienilampi is coming later. Enjoy the water for now.'],['Ruovikko tihenee. Seuraa rantaa takaisin mökille.','The reeds thicken here. Follow the bank back to the cabin.'],['Polku ei jatku vielä pidemmälle.','The trail beyond is not open yet.']);
  let lang='en';try{lang=localStorage.getItem('timbertrail-language')==='fi'?'fi':'en';}catch{}
  const exact=[new Map(),new Map()], entries=[[],[]];
  for(const [fi,en]of pairs){exact[0].set(fi,en);exact[1].set(en,fi);entries[0].push([fi,en]);entries[1].push([en,fi]);}
  for(const e of entries)e.sort((a,b)=>b[0].length-a[0].length);
  const escape=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
  const patterns=entries.map(e=>new RegExp(e.map(([s])=>escape(s)).join('|'),'g'));
  function text(value){const str=String(value??''),i=lang==='en'?0:1;if(exact[i].has(str))return exact[i].get(str);return str.replace(patterns[i],s=>exact[i].get(s)||s);}
  const sources=new WeakMap();
  function translate(node,key,value,set){let record=sources.get(node);if(!record){record={};sources.set(node,record);}let old=record[key];if(!old||old.last!==value)old={source:value};const next=text(old.source);set(next);record[key]={source:old.source,last:next};}
  function apply(scope){if(!root.document?.createTreeWalker)return;const walker=document.createTreeWalker(scope,4);let n;while(n=walker.nextNode()){if(!['SCRIPT','STYLE'].includes(n.parentElement?.tagName))translate(n,'text',n.nodeValue,v=>n.nodeValue=v);}const all=scope.querySelectorAll?.('[title],[aria-label],[alt]')||[];for(const el of all)for(const k of ['title','aria-label','alt'])if(el.hasAttribute(k))translate(el,k,el.getAttribute(k),v=>el.setAttribute(k,v));document.documentElement.lang=lang;}
  root.L={text,apply,get lang(){return lang;},set(value){lang=value==='fi'?'fi':'en';try{localStorage.setItem('timbertrail-language',lang);}catch{}apply(document);}};
})(typeof window==='undefined'?globalThis:window);
