/* Timbertrail — illustrated encounters and regional field map. */
window.TimberPanels = {
  dialogue(stage, repeat) {
    const scenes = {
      welcome: ["Come in. Mind the shavings.", "The old man turns a half-carved kuksa in his hands. Coffee steams beside the knife. “Aarni. Been keeping this stove warm longer than I care to count. What brings you along my trail?”", [["trail", "I am looking for a place to make camp."], ["cup", "That is a beautiful kuksa."]]],
      trail: ["A little shelter goes a long way.", "“Dry ground, a roof, and enough split wood for the night. That is a good beginning. The old cabins further out could use a pair of willing hands, one day.”", [["offer", "Could we exchange a few supplies?"], ["cup", "Do you make everything yourself?"]]],
      cup: ["Birch remembers the shape of your hand.", "“Slow work. A sharp puukko, a little patience. This one is for a friend.” He brushes a curl of wood from the table. “Keep your own blade sharp. You will need it to dress game.”", [["offer", "What supplies do you have?"], ["trail", "What should I know about this forest?"]]],
      offer: ["We can help each other along.", "“A good hide or a couple of cooked fish for my spare compass. I have arrows too. Nothing here needs to be hurried.”", [["trade", "Let us see what we can trade."]]],
      smalltalk: ["The kettle is still warm.", repeat % 2 ? "“Heard a grouse beyond the stream this morning. Just the one.” Aarni sets his carving down. “How is your camp coming along?”" : "“Rain or shine, there is always a little wood to split.” Aarni smiles over his coffee. “Need anything for the trail?”", [["trade", "Let us trade."], ["cup", "How is the carving coming along?"]]]
    };
    const [title, speech, choices] = scenes[stage] || scenes.welcome;
    return `<div class="encounter"><img src="assets/timber-interior.png" alt="Aarni carving a kuksa at his cabin table, beside a steaming coffee cup."><div class="conversation"><div class="speaker">AARNI <span>· The cabin keeper</span></div><h3>${title}</h3><p>${speech}</p><div class="reply-list">${choices.map(([id,label],i)=>`<button data-reply="${id}"><span>0${i+1}</span>${label}<b>↗</b></button>`).join('')}</div></div></div>`;
  },
  trade(s,art) {
    const offers = [['compass','Compass + 8 arrows','1 hide OR 2 cooked fish',s.inventory.hide>0||s.inventory.cookedFish>=2],['arrows','8 arrows','5 dry branches',s.inventory.wood>=5],['puukko','Birch-handled puukko','1 hide',s.inventory.hide>0],['axe','Steel trail axe','2 hides',s.inventory.hide>=2]];
    return `<div class="trader-banner"><img src="assets/timber-interior.png" alt="Aarni’s log cabin"><p>“A fair exchange. Take what you need for the trail.”</p></div><div class="camp-view"><div class="camp-options">${offers.map(([id,title,cost,ok])=>`<button data-trade="${id}" ${ok?'':'disabled'}>${art(id)}<strong>${title}</strong><small>${cost}</small></button>`).join('')}</div><p>In your pack: ${s.inventory.hide} × Hide · ${s.inventory.cookedFish} × Cooked fish · ${s.inventory.wood} × Dry branch</p><button class="text-button" data-reply="smalltalk">← Back to conversation</button></div>`;
  },
  fire(s,engine,art,name) {
    const fire=s.structures.find(f=>f.id===engine.activeFire),lit=fire?.lit, fuel=Math.ceil(fire?.fuel||0);
    return `<div class="camp-view"><div class="fire-status"><span>${lit?'♨':'◇'}</span><div><h3>${lit?'A steady warmth':'Cold embers'}</h3><p>${fuel} s · Fuel remaining (game time)</p></div></div><p>Add dry branches or split billets. The fire dies when its fuel runs out. Time pauses while this window is open.</p><div class="camp-options">${['wood','firewood'].map(id=>`<button data-fuel="${id}" ${s.inventory[id]>0?'':'disabled'}>${art(id)}Add ${name(id)}<small>${s.inventory[id]} × · +${id==='wood'?45:150} s</small></button>`).join('')}</div><div class="camp-options">${[['rawFish','cookedFish'],['rawMeat','cookedMeat']].map(([raw,cooked])=>`<button data-cook="${raw}" ${lit&&s.inventory[raw]?'':'disabled'}>${art(cooked)}${name(cooked)}<small>${s.inventory[raw]} × ${name(raw)}</small></button>`).join('')}</div><p>${lit?'Stand near the fire to warm up.':'Add fuel before cooking.'}</p></div>`;
  },
  map() {
    let marks='';
    for(let i=0;i<170;i++){const x=25+PE.random(i)*690,y=65+PE.random(i+99)*320;marks+=`<path d="M${x} ${y}l-5 9h10z m0 5l-7 12h14z" fill="${x<400?'#526248':'#77765d'}" opacity=".23"/>`;}
    for(let i=0;i<15;i++){const x=410+PE.random(i+17)*280,y=50+PE.random(i+44)*100;marks+=`<path d="M${x-19} ${y+29}l19-29 22 29m-22-29 3 16 8 2" fill="none" stroke="#706d5a" opacity=".5"/>`;}
    const nodes=[['forest','Forest',26,51,true],['woods','Deep woods',45,29],['burnt','Burnt forest',23,80],['river','Riverbank',61,70],['fell','Fell',65,41],['mountain','Mountain',84,23]];
    return `<div class="map-view"><div class="paper-map regional-map"><svg viewBox="0 0 740 440" aria-hidden="true"><defs><pattern id="folds" width="148" height="110" patternUnits="userSpaceOnUse"><path d="M148 0H0V110" fill="none" stroke="#716349" opacity=".16"/></pattern></defs><rect width="740" height="440" fill="url(#folds)"/>${marks}<path d="M528 -20C465 60 525 113 471 174S518 240 434 300 459 382 382 460" fill="none" stroke="#688986" stroke-width="13" opacity=".55"/><path d="M528 -20C465 60 525 113 471 174S518 240 434 300 459 382 382 460" fill="none" stroke="#d0d6bb" stroke-width="3"/><path d="M180 352Q235 289 192 225T330 130Q410 212 475 178T620 100M192 225Q322 348 445 308" fill="none" stroke="#8e7855" stroke-width="2" stroke-dasharray="4 6"/><g transform="translate(671 354)" stroke="#66634e" fill="none"><circle r="27"/><path d="M0-37V37M-37 0H37M0-29L7 9 0 1-7 9Z"/><text x="-5" y="-43" fill="#66634e" stroke="none" font-family="Georgia">N</text></g></svg><div class="map-heading">Timbertrail<small>THE NORTHERN TRAILS</small></div>${nodes.map(([id,title,x,y,active])=>`<button class="region-pin ${active?'available':''}" style="left:${x}%;top:${y}%" ${active?'data-travel="forest"':'disabled'}><b>${active?'◆':'◇'}</b>${title}<small>${active?'CURRENT REGION':'UNEXPLORED'}</small></button>`).join('')}<span class="cabin-pin" style="left:48%;top:50%" title="Future safe house · Restore this cabin">⌂<small>Old cabin</small></span><span class="cabin-pin" style="left:80%;top:62%" title="Future safe house · Restore this cabin">⌂<small>Ridge cabin</small></span><span class="map-caption">Grey locations will open in a future chapter.</span></div><div class="map-info"><div><h3>Forest</h3><p>Mossy timber, clear water, and quiet trails.</p></div><button class="primary" data-travel="forest">Return to camp <span>⟶</span></button></div></div>`;
  },
  settings() {return `<div class="settings-view"><p class="eyebrow">LANGUAGE / KIELI</p><h3>A familiar voice on the trail</h3><div class="language-options"><button data-language="en" aria-pressed="${L.lang==='en'}"><strong>English</strong><small>English</small></button><button data-language="fi" aria-pressed="${L.lang==='fi'}"><strong>Suomi</strong><small>Finnish</small></button></div><p>Your language choice is saved on this device. Your journey is unchanged.</p><button class="settings-audio" data-audio="true">♪ <span>Toggle forest sounds</span></button><div class="reset-journey"><p class="eyebrow">JOURNEY</p><h3>Start from the beginning</h3><p>Reset your current journey. Your language preference is kept, and older legacy saves remain untouched.</p><button class="text-button" data-panel="confirm">Reset current journey <span>↗</span></button></div><button class="text-button settings-back" data-cancel="true">← Close settings</button></div>`;}
};
