/* Timbertrail — illustrated encounters and regional field map. */
window.TimberPanels = {
  dialogue(stage, repeat) {
    const scenes = {
      welcome: ["Come in. Mind the shavings.", "The old man turns a half-carved kuksa in his hands. Coffee steams beside the knife. “Aarni. Been keeping this stove warm longer than I care to count. What brings you along my trail?”", [["trail", "I am looking for a place to make camp."], ["cup", "That is a beautiful kuksa."]]],
      trail: ["A little shelter goes a long way.", "“Dry ground, a roof, and enough split wood for the night. That is a good beginning. The old cabins further out could use a pair of willing hands, one day.”", [["offer", "Could we exchange a few supplies?"], ["cup", "Do you make everything yourself?"]]],
      cup: ["Birch remembers the shape of your hand.", "“Slow work. A sharp puukko, a little patience. This one is for a friend.” He brushes a curl of wood from the table. “Keep your own blade sharp. You will need it to dress game.”", [["offer", "What supplies do you have?"], ["trail", "What should I know about this forest?"]]],
      offer: ["We can help each other along.", "“Two hides for a sturdy canteen. Fill it at a spring and carry a drink for the trail. I have arrows too. Nothing here needs to be hurried.”", [["trade", "Let us see what we can trade."]]],
      smalltalk: ["The kettle is still warm.", repeat % 2 ? "“Heard a grouse beyond the stream this morning. Just the one.” Aarni sets his carving down. “How is your camp coming along?”" : "“Rain or shine, there is always a little wood to split.” Aarni smiles over his coffee. “Need anything for the trail?”", [["trade", "Let us trade."], ["cup", "How is the carving coming along?"]]]
    };
    const [title, speech, choices] = scenes[stage] || scenes.welcome;
    return `<div class="encounter"><img src="assets/timber-interior.png" alt="Aarni carving a kuksa at his cabin table, beside a steaming coffee cup."><div class="conversation"><div class="speaker">AARNI <span>· The cabin keeper</span></div><h3>${title}</h3><p>${speech}</p><div class="reply-list">${choices.map(([id,label],i)=>`<button data-reply="${id}"><span>0${i+1}</span>${label}<b>↗</b></button>`).join('')}</div></div></div>`;
  },
  trade(s,art) {
    const offers = [['canteen','Canteen','2 hides',s.inventory.hide>=2&&!s.inventory.canteen&&!s.cabinHome?.storage?.canteen],['arrows','8 arrows','5 dry branches',s.inventory.wood>=5],['puukko','Birch-handled puukko','1 hide',s.inventory.hide>0],['axe','Steel trail axe','2 hides',s.inventory.hide>=2]];
    return `<div class="trader-banner"><img src="assets/timber-interior.png" alt="Aarni’s log cabin"><p>“A fair exchange. Take what you need for the trail.”</p></div><div class="camp-view"><div class="camp-options">${offers.map(([id,title,cost,ok])=>`<button data-trade="${id}" ${ok?'':'disabled'}>${art(id)}<strong>${title}</strong><small>${cost}</small></button>`).join('')}</div><p>In your pack: ${s.inventory.hide} × Hide · ${s.inventory.cookedFish} × Cooked fish · ${s.inventory.wood} × Dry branch</p><button class="text-button" data-reply="smalltalk">← Back to conversation</button></div>`;
  },
  fire(s,engine,art,name) {
    const fire=s.structures.find(f=>f.id===engine.activeFire),lit=fire?.lit, fuel=Math.ceil(fire?.fuel||0);
    return `<div class="camp-view"><div class="fire-status"><span>${lit?'♨':'◇'}</span><div><h3>${lit?'A steady warmth':'Cold embers'}</h3><p>${fuel} s · Fuel remaining (game time)</p></div></div><p>Add dry branches or split billets. The fire dies when its fuel runs out. Time pauses while this window is open.</p><div class="camp-options">${['wood','firewood'].map(id=>`<button data-fuel="${id}" ${s.inventory[id]>0?'':'disabled'}>${art(id)}Add ${name(id)}<small>${s.inventory[id]} × · +${id==='wood'?45:150} s</small></button>`).join('')}</div><div class="camp-options">${[['rawFish','cookedFish'],['rawMeat','cookedMeat']].map(([raw,cooked])=>`<button data-cook="${raw}" ${lit&&s.inventory[raw]?'':'disabled'}>${art(cooked)}${name(cooked)}<small>${s.inventory[raw]} × ${name(raw)}</small></button>`).join('')}</div><p>${lit?'Stand near the fire to warm up.':'Add fuel before cooking.'}</p></div>`;
  },
  map(s={currentMap:'forest',visited:{forest:true}}) {
    const nodes=[...Object.entries(PERegions.maps).map(([id,m])=>[id,m.name,...m.point,PERegions.canTravel(s,id)]),['mountain','High mountains',73,28,false],['winter','Winter fells',28,65,false],['plains','Open plains',73,68,false]];
    const descriptions={...Object.fromEntries(Object.entries(PERegions.maps).map(([id,m])=>[id,m.description])),mountain:'High mountains · a demanding future endgame region.',winter:'Winter fells · snowy woodland, cold winds and future trails.',plains:'Open plains · future hunting grounds and rare wildlife.'};
    return `<div class="map-view illustrated-map"><div class="map-sheet regional-map"><img class="map-art" src="assets/trail-map.png" alt="Hand-drawn map of forests, a central river, snowy fells, high mountains and open plains."><svg class="map-trails" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path d="M27 30 Q31 31 35 35 L34.5 41"/></svg>${nodes.map(([id,title,x,y,available])=>`<button class="region-pin ${PERegions.maps[id]?'mapped':''} ${available?'available':''} ${s.visited?.[id]?'visited':''} ${id===s.currentMap?'current':''}" style="left:${x}%;top:${y}%" ${available?'data-travel="'+id+'"':'data-region="'+id+'"'} aria-label="${title}" aria-describedby="region-${id}-description" ${id===s.currentMap?'aria-current="location"':''}><span class="region-dot"></span><span class="region-name" id="region-${id}-description" role="tooltip">${title}<small>${id===s.currentMap?'CURRENT REGION':s.visited?.[id]?'VISITED':available?'OPEN TRAIL':'UNEXPLORED'}</small><span class="region-description">${descriptions[id]}</span></span></button>`).join('')}<span class="cabin-pin" style="left:38%;top:42%" tabindex="0" title="Sienilampi · cabin restoration">⌂</span></div></div>`;
  },
  settings() {const mix=PEAudio.settings();return `<div class="settings-view"><p class="eyebrow">LANGUAGE / KIELI</p><h3>A familiar voice on the trail</h3><div class="language-options"><button data-language="en" aria-pressed="${L.lang==='en'}"><strong>English</strong><small>English</small></button><button data-language="fi" aria-pressed="${L.lang==='fi'}"><strong>Suomi</strong><small>Finnish</small></button></div><p>Your language choice is saved on this device. Your journey is unchanged.</p><div class="audio-settings">${[['sound','Forest & actions','soundOn','soundVolume'],['music','Music','musicOn','musicVolume']].map(([id,label,on,volume])=>`<div class="audio-setting"><div><label for="volume-${id}">${label}</label><button data-audio-channel="${on}" role="switch" aria-checked="${mix[on]}" aria-label="${label}">${mix[on]?'On':'Off'}</button></div><input id="volume-${id}" type="range" min="0" max="100" step="1" value="${Math.round(mix[volume]*100)}" data-audio-volume="${volume}"><output id="volume-value-${volume}">${Math.round(mix[volume]*100)}%</output></div>`).join('')}</div><div class="reset-journey"><p class="eyebrow">JOURNEY</p><h3>Start from the beginning</h3><p>Reset your current journey. Your language preference is kept, and older legacy saves remain untouched.</p><button class="text-button" data-panel="confirm">Reset current journey <span>↗</span></button></div><button class="text-button settings-back" data-cancel="true">← Close settings</button></div>`;}
};
