const assert=require('node:assert/strict'),PE=require('../engine.js'),C=require('../cabin-interior.js'),R=require('../regions.js');
const step=(e,n=22)=>{for(let i=0;i<n;i++)e.update(.05);};
function room(){const e=new PE.Engine();e.start();e.enterRegion('pond',R.cabin.x);e.state.cabinRepairs={roof:true,facade:true,yard:true};assert.equal(C.begin(e,true),true);step(e);return e;}
const e=room(),h=C.home(e),events=[];e.onEvent=v=>events.push(v);assert.equal(h.inside,true);const worldX=e.state.player.x;assert.equal(h.x,320);e.keys.KeyD=true;step(e,20);assert.ok(h.x>420);assert.equal(e.state.player.x,worldX);assert.equal(e.state.player.running,false);e.keys={};assert.equal(C.interact(e,'chest'),false);assert.equal(e.roomTarget,null);assert.equal(e.state.player.moving,false);e.keys.KeyA=true;step(e,1);assert.equal(e.roomTarget,null);e.keys={};
Object.assign(e.state.inventory,{wood:12,knife:1});e.state.toolDurability.knife=7;h.x=877;assert.equal(C.transfer(e,'wood','store',true),true);assert.equal(h.storage.wood,12);assert.equal(e.state.inventory.wood,0);assert.equal(C.transfer(e,'wood','take'),true);assert.equal(e.state.inventory.wood,1);assert.equal(C.transfer(e,'knife','store'),true);assert.deepEqual(h.tools.knife,[7]);assert.equal(C.transfer(e,'knife','take'),true);assert.equal(e.state.toolDurability.knife,7);h.tools.knife.push(3);assert.notEqual(C.transfer(e,'knife','take'),true);assert.deepEqual(h.tools.knife,[3]);
const before=e.save();assert.equal(C.transfer(e,'unknown','store'),false);assert.equal(C.transfer(e,'wood','bad'),false);assert.equal(e.save(),before);h.x=100;assert.equal(C.transfer(e,'wood','store'),false);h.x=877;h.storage.stone=200;assert.equal(C.transfer(e,'wood','store'),false);h.storage.stone=0;
const reload=new PE.Engine();reload.start(JSON.parse(e.save()));assert.equal(reload.state.cabinHome.inside,true);assert.equal(reload.state.toolDurability.knife,7);assert.deepEqual(reload.state.cabinHome.tools.knife,[3]);assert.equal(reload.state.cabinHome.storage.wood,11);assert.equal(C.restore(null,PE.items,PE.toolDurability).inside,false);
h.x=465;e.state.inventory.rawMeat=1;assert.equal(C.action(e,'rawMeat'),false);e.state.inventory.wood=2;assert.equal(C.action(e,'wood'),true);assert.equal(h.fire.fuel,45);const warmth=e.state.player.warmth;step(e,20);assert.ok(h.fire.fuel<45);assert.ok(e.state.player.warmth>warmth);assert.equal(C.action(e,'rawMeat'),true);assert.equal(e.state.inventory.cookedMeat,1);assert.equal(C.action(e,'extinguish'),true);const fuel=h.fire.fuel;step(e,10);assert.equal(h.fire.fuel,fuel);assert.equal(C.action(e,'relight'),true);
h.x=719;e.state.player.thirst=2;assert.equal(C.interact(e,'coffee'),true);assert.equal(e.state.player.thirst,100);assert.equal(h.cupFull,false);e.state.player.thirst=20;assert.equal(C.interact(e,'coffee'),false);assert.equal(e.state.player.thirst,20);h.x=776;C.interact(e,'jug');assert.equal(h.cupFull,true);h.x=740;C.interact(e,'window');assert.equal(h.shutters,false);h.x=625;C.interact(e,'lantern');assert.equal(h.lantern,false);h.x=572;C.interact(e,'kajo');assert.equal(e.roomHeart,1.2);step(e,26);assert.equal(e.roomHeart,0);
h.x=886;const day=e.state.day;e.state.dayTime=.85;e.state.player.energy=4;h.fire={fuel:100,lit:true};assert.equal(C.action(e,'sleep'),true);step(e);assert.equal(e.state.day,day+1);assert.ok(Math.abs(e.state.dayTime-.28)<.001);assert.equal(e.state.player.energy,100);assert.equal(h.fire.lit,false);assert.equal(h.inside,true);assert.equal(C.action(e,'unknown'),false);
h.x=132;h.fire={fuel:80,lit:true};C.interact(e,'door');step(e);assert.equal(h.inside,false);assert.equal(e.state.player.x,R.cabin.x);step(e,20);assert.ok(h.fire.fuel<80);e.enterRegion('forest',R.aarni.x);step(e,20);assert.ok(h.fire.fuel<79,'home fire advances across outdoor regions');
const trader=new PE.Engine();trader.start();trader.state.player.x=trader.npc.x;trader.finishDialogue();trader.state.inventory.hide=2;assert.notEqual(trader.trade('canteen'),false);assert.equal(trader.state.inventory.hide,0);assert.equal(trader.state.inventory.canteen,1);assert.equal(trader.state.canteenFull,false);trader.state.inventory.hide=4;assert.equal(trader.trade('canteen'),false);assert.equal(trader.state.inventory.hide,4);assert.equal(trader.trade('compass'),false);
trader.state.player.x=trader.water[0].x;trader.interact(trader.water[0]);assert.equal(trader.state.canteenFull,true);trader.state.player.thirst=1;assert.equal(trader.use('canteen'),true);assert.equal(trader.state.player.thirst,100);assert.equal(trader.state.inventory.canteen,1);trader.state.player.thirst=3;assert.equal(trader.use('canteen'),false);assert.equal(trader.state.player.thirst,3);trader.interact(trader.water[0]);assert.equal(trader.state.canteenFull,true);
const old=new PE.Engine();old.start({version:6,inventory:{compass:1}});assert.equal(old.state.inventory.canteen,1);assert.equal(old.state.inventory.compass,undefined);const reloadBottle=new PE.Engine();reloadBottle.start(JSON.parse(trader.save()));assert.equal(reloadBottle.state.canteenFull,true);
const carried=room();carried.state.inventory.canteen=1;carried.state.canteenFull=true;C.home(carried).x=877;C.transfer(carried,'canteen','store');C.transfer(carried,'canteen','take');assert.equal(carried.state.canteenFull,true);assert.equal(carried.state.inventory.canteen,1);
assert.ok(PE.needDamage.warmth<PE.needDamage.hunger&&PE.needDamage.hunger<PE.needDamage.thirst);assert.ok(PE.needDamage.warmth<.03);for(const key of ['hunger','thirst','warmth','energy']){const test=room();test.state.player[key]=0;test.state.player.health=80;test.update(.05);assert.ok(Math.abs(test.state.player.health-(80-PE.needDamage[key]*.05))<1e-7);}
assert.equal(require('../terrain-surface.js').areas('river').length,0);for(const cam of [2200,2700,3100]){const [x,y,w,height]=R.trailBox(cam);assert.equal(x-cam, R.trail.backdropX-Math.round(cam/(6400-960)*(3280-960))-65);assert.ok(y<300&&w>0&&height>0);}
for(const f of C.fixtures){h.x=Math.max(C.camera.min,Math.min(C.camera.max,f.x));const p={x:f.x,y:f.box[1]+f.box[3]/2},screen=C.toScreen(e,p),back=C.toRoom(e,screen);assert.ok(Math.abs(p.x-back.x)<1e-8&&Math.abs(p.y-back.y)<1e-8);assert.equal(C.hit(screen,e)?.id,f.id,'projected hit: '+f.id);}
const nav=room(),nh=C.home(nav);assert.equal(C.visible(nav,'bed'),false);assert.equal(C.visible(nav,'door'),true);nav.keys={KeyA:true};step(nav,80);assert.equal(nh.x,320);nav.keys={KeyD:true};step(nav,100);assert.equal(nh.x,640);assert.equal(C.visible(nav,'door'),false);assert.equal(C.visible(nav,'bed'),true);assert.equal(nav.state.player.moving,false);nav.keys={};const migrated=C.restore({x:900},PE.items,PE.toolDurability);assert.equal(migrated.x,640);
require('../render.js');const art=require('../cabin-art.js'),sprites=[],transforms=[],images=[],ctx=new Proxy({setTransform(...a){transforms.push(a);},drawImage(...a){images.push(a[0]);},createRadialGradient(){return {addColorStop(){}};},createLinearGradient(){return {addColorStop(){}};}},{get:(o,k)=>o[k]||(()=>{})});const painting={},seat={};const renderer={c:ctx,cabinInterior:painting,seatedImage:seat,surface:{},canvas:{width:960,height:540,getContext:()=>ctx},sprite(...args){sprites.push(args);}};nav.roomRest=true;nav.state.player.warmth=65;art.draw(renderer,nav);assert.deepEqual(sprites.map(a=>a[0]),[7],'only Kajo, never standing/seated player');assert.equal(sprites[0][4],.21);assert.ok(!images.includes(seat));assert.ok(transforms.some(t=>t[0]===1.5&&t[3]===1.5&&t[4]===-480&&t[5]===-126));
console.log('PASS cabin entry/exit, indoor movement, storage conservation/tool wear, persistence, fuel/cooking/sleep, mug/jug, decor, canteen trade/refill/reuse/migration, need rates and distant trail projection.');
