// A deliberately non-browser DOM/event harness: verifies integration, not CSS layout.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const dir=path.resolve(__dirname,'..');
const decode=t=>t.replaceAll('&amp;','&').replaceAll('&lt;','<').replaceAll('&gt;','>');
class Element {
 constructor(tag,doc){this.tagName=tag.toUpperCase();this.ownerDocument=doc;this.children=[];this.parentElement=null;this.attributes={};this.dataset={};this.style={};this.listeners={};this.hidden=false;this.disabled=false;this.scrollTop=0;this._text='';this.width=300;this.height=150;}
 get id(){return this.attributes.id||'';}set id(v){this.setAttribute('id',v);}get className(){return this.attributes.class||'';}set className(v){this.attributes.class=v;}
 get classList(){const el=this;return{contains:k=>el.className.split(/\s+/).includes(k),add(...ks){el.className=[...new Set([...el.className.split(/\s+/),...ks])].join(' ').trim();},remove(...ks){el.className=el.className.split(/\s+/).filter(k=>!ks.includes(k)).join(' ');},toggle(k,v){const yes=v===undefined?!this.contains(k):v;yes?this.add(k):this.remove(k);return yes;}};}
 setAttribute(k,v){v=String(v);this.attributes[k]=v;if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;if(k==='hidden')this.hidden=true;if(k==='disabled')this.disabled=true;if(k==='width'||k==='height')this[k]=Number(v);}
 hasAttribute(k){return k in this.attributes;}getAttribute(k){return this.attributes[k]??null;}get textContent(){return this._text+this.children.map(c=>c.textContent).join('');}set textContent(v){this._text=String(v);this.children=[];}
 set innerHTML(html){this.children=[];this._text='';parse(html,this);}get innerHTML(){return this.children.map(c=>'<'+c.tagName+'>'+c.innerHTML+'</'+c.tagName+'>').join('')+this._text;}
 get firstElementChild(){return this.children[0]||null;}
 append(el){el.parentElement=this;this.children.push(el);}get isConnected(){return this===this.ownerDocument||!!this.parentElement?.isConnected;}
 matches(selector){if(selector.includes(','))return selector.split(',').some(s=>this.matches(s.trim()));const not=selector.match(/:not\(([^)]+)\)/);if(not&&this.matches(not[1]))return false;selector=selector.replace(/:not\([^)]+\)/g,'');const tag=selector.match(/^[\w-]+/);if(tag&&tag[0].toUpperCase()!==this.tagName)return false;for(const m of selector.matchAll(/#([\w-]+)/g))if(this.id!==m[1])return false;for(const m of selector.matchAll(/\.([\w-]+)/g))if(!this.classList.contains(m[1]))return false;for(const m of selector.matchAll(/\[([\w-]+)(?:="([^"]*)")?\]/g)){if(m[1]==='disabled'){if(!this.disabled)return false;}else if(!(m[1] in this.attributes))return false;if(m[2]!==undefined&&this.getAttribute(m[1])!==m[2])return false;}return true;}
 querySelectorAll(selector){const result=[];for(const c of this.children){if(c.matches(selector))result.push(c);result.push(...c.querySelectorAll(selector));}return result;}querySelector(s){return this.querySelectorAll(s)[0]||null;}closest(s){return this.matches(s)?this:this.parentElement?.closest(s)||null;}
 addEventListener(type,fn){(this.listeners[type]??=[]).push(fn);}dispatch(type,extra={}){const event={target:this,preventDefault(){},...extra};for(let el=this;el;el=el.parentElement)for(const f of el.listeners[type]||[])f(event);}
 focus(){this.ownerDocument.activeElement=this;}getBoundingClientRect(){return{left:0,top:0,width:960,height:540};}requestFullscreen(){this.ownerDocument.fullscreenElement=this;return Promise.resolve();}
 getContext(){return new Proxy({createImageData:(w,h)=>({data:new Uint8ClampedArray(w*h*4)}),measureText:t=>({width:t.length*8}),createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}})},{get:(o,k)=>o[k]||(()=>{}),set:(o,k,v)=>(o[k]=v,true)});}
}
function parse(html,parent){const stack=[parent];for(const token of html.match(/<!--[\s\S]*?-->|<[^>]+>|[^<]+/g)||[]){if(token.startsWith('<!--')||token.startsWith('<!'))continue;if(token.startsWith('</')){if(stack.length>1)stack.pop();continue;}if(token[0]==='<'){const m=token.match(/^<([\w-]+)/);if(!m)continue;const el=new Element(m[1],parent.ownerDocument);for(const a of token.slice(m[0].length).matchAll(/([\w-]+)(?:="([^"]*)"|='([^']*)'|=([^\s>]+))?/g))el.setAttribute(a[1],decode(a[2]??a[3]??a[4]??''));stack.at(-1).append(el);if(!['meta','link','br','hr','img','input'].includes(m[1])&&!token.endsWith('/>'))stack.push(el);}else stack.at(-1)._text+=decode(token);}}
const doc=new Element('document',null);doc.ownerDocument=doc;doc.createElement=t=>new Element(t,doc);doc.getElementById=id=>doc.querySelector('#'+id);doc.hidden=false;doc.exitFullscreen=()=>Promise.resolve();parse(fs.readFileSync(path.join(dir,'index.html'),'utf8'),doc);
doc.documentElement=doc.querySelector('html');doc.createTreeWalker=scope=>{const nodes=[];function visit(el){if(el._text){if(!el._textNode)el._textNode={parentElement:el,get nodeValue(){return el._text;},set nodeValue(v){el._text=v;}};nodes.push(el._textNode);}for(const c of el.children)visit(c);}visit(scope);let i=0;return{nextNode:()=>nodes[i++]||null};};
const storage=new Map([['pine-and-ember-save-v1',JSON.stringify({player:{x:565},inventory:{wood:40,stone:30,fiber:30,berries:3,knife:1,bow:1,arrows:4},completed:{makeKnife:true}})]]);
let raf;const imageLoads=[];class TestImage{get src(){return this._src;}set src(value){this._src=value;imageLoads.push(Promise.resolve().then(()=>{const b=fs.readFileSync(path.join(dir,value));this.width=b.readUInt32BE(16);this.height=b.readUInt32BE(20);this.onload?.();}));}}
let timerId=0;const timers=new Map();const advance=()=>{for(let pass=0;pass<8;pass++){const batch=[...timers].filter(([,v])=>v.delay<=350);for(const [id,v]of batch){timers.delete(id);v.fn();}}};
const context={document:doc,Image:TestImage,console,performance,setTimeout:(fn,delay)=>(timers.set(++timerId,{fn,delay}),timerId),clearTimeout:id=>timers.delete(id),requestAnimationFrame:fn=>{raf=fn;},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},addEventListener(){},};context.window=context;context.globalThis=context;


vm.createContext(context);for(const file of ['i18n.js','regions.js','cabin-interior.js','engine.js','item-icons.js','equipment.js','fire-effects.js','render.js','panels.js','storage-ui.js'])vm.runInContext(fs.readFileSync(path.join(dir,file),'utf8'),context,{filename:file});
let engine;const Base=context.PE.Engine;context.PE.Engine=class extends Base{constructor(...a){super(...a);if(!engine)engine=this;}};
const sounds=[],mix={soundOn:true,musicOn:true,soundVolume:.7,musicVolume:.4};context.PEAudio={play(n){sounds.push(n);},start(){},toggle(){return false;},pause(){},update(){},settings:()=>({...mix}),configure:p=>Object.assign(mix,p)};
vm.runInContext(fs.readFileSync(path.join(dir,'game.js'),'utf8'),context,{filename:'game.js'});
const $=id=>doc.getElementById(id),click=sel=>{const b=doc.querySelector(sel);assert.ok(b,'Element exists: '+sel);assert.equal(b.disabled,false);b.dispatch('click');};
(async()=>{await Promise.all(imageLoads);await Promise.resolve();await Promise.resolve();
assert.equal($('title-card').querySelector('.eyebrow'),null);assert.equal($('title-card').querySelector('.title-rule'),null);assert.equal($('title-card').querySelector('.title-foot'),null);assert.equal($('load-note').textContent,'');assert.equal($('title-card').querySelectorAll('.menu-scroll').length,2);
const englishTasks=['Gather branches, stones, and fibre','Craft a flint knife','Craft a flint axe','Build a campfire','Build a lean-to','Drink fresh water','Meet Aarni','Trade with Aarni','Cook a warm meal'];assert.deepEqual(Array.from(context.PE.tasks,([,label])=>context.L.text(label)),englishTasks);context.L.set('fi');assert.equal(context.L.text('Craft a flint axe'),'Valmista piikivikirves');context.L.set('en');
assert.equal(context.L.lang,'en');assert.equal($('start-button').disabled,false);
click('#continue-button');assert.equal(engine.state.inventory.wood,40);assert.ok(storage.has('timbertrail-save-v3'));
click('#journal-button');assert.ok($('modal').classList.contains('is-opening'));assert.equal($('book-animation').src,'assets/book-opening-1.png');advance();assert.ok(!$('modal').classList.contains('is-opening'));assert.ok($('game-shell').classList.contains('journal-open'));
assert.equal($('quick-tools').querySelectorAll('[data-slot="knife"]').length,1);assert.equal($('quick-tools').querySelectorAll('[data-slot="axe"]').length,1);
assert.equal(engine.assignQuickSlot('knife','wood'),false);assert.equal(engine.assignQuickSlot('knife','knife'),true);assert.equal(engine.assignQuickSlot('food','berries'),true);assert.equal(engine.assignQuickSlot('axe','knife'),false);
click('[data-panel="craft"]');assert.ok(sounds.includes('pageFlip'));click('[data-panel="map"]');assert.ok(doc.querySelector('.regional-map'));click('[data-panel="journal"]');
click('#close-modal');assert.equal($('book-animation').src,'assets/book-open.png');advance();assert.equal($('modal-backdrop').hidden,true);assert.ok(!$('game-shell').classList.contains('journal-open'));assert.ok(sounds.filter(x=>x==='pageTurn').length>=2);
console.log('PASS Journal frame order, tabs/audio events, one typed tool slot, save migration and boot. DOM harness only; not browser layout QA.');
doc.dispatch('keydown',{code:'Tab'});advance();assert.equal($('modal').dataset.panel,'inventory');
const item=doc.querySelector('[data-item-drag="knife"]'),target=doc.querySelector('[data-slot="knife"]');let transfer='';const dataTransfer={setData:(_,v)=>transfer=v,getData:()=>transfer};item.dispatch('dragstart',{dataTransfer});assert.ok(target.classList.contains('drop-ready'));target.dispatch('drop',{dataTransfer});assert.equal(engine.state.quickTools.knife,'knife');
click('[data-panel="map"]');assert.equal(doc.querySelectorAll('.region-pin').length,6);assert.equal(doc.querySelectorAll('.region-pin.available').length,2);const beforeX=engine.state.player.x;click('[data-region="mountain"]');assert.equal(engine.state.player.x,beforeX);assert.ok($('region-mountain-description').textContent.includes('future endgame'));assert.equal(doc.querySelector('.map-info'),null);click('#close-modal');advance();
click('[data-panel="settings"]');assert.equal(doc.querySelectorAll('input[data-audio-volume]').length,2);click('[data-audio-channel="musicOn"]');assert.equal(mix.musicOn,false);assert.equal(mix.soundOn,true);const slider=$('volume-music');slider.value='27';slider.dispatch('input');assert.equal(mix.musicVolume,.27);click('[data-language="fi"]');assert.ok($('modal-content').textContent.includes('Musiikki'));click('[data-language="en"]');
console.log('PASS Tab shortcut, actual drag/drop events, map region availability and independent audio controls.');
click('#close-modal');advance();
doc.dispatch('keydown',{code:'Tab'});advance();assert.equal($('modal-backdrop').hidden,false);
doc.dispatch('keydown',{code:'Tab',repeat:true});assert.ok(!$('modal').classList.contains('is-closing'),'held Tab cannot immediately close the book');
doc.dispatch('keydown',{code:'Tab'});assert.ok($('modal').classList.contains('is-closing'));advance();assert.equal($('modal-backdrop').hidden,true);
doc.dispatch('keydown',{code:'KeyS'});assert.equal(engine.state.player.crouching,true);
doc.dispatch('keydown',{code:'KeyS',repeat:true});assert.equal(engine.state.player.crouching,true);
doc.dispatch('keyup',{code:'KeyS'});doc.dispatch('keydown',{code:'KeyS'});assert.equal(engine.state.player.crouching,false);
doc.dispatch('keydown',{code:'KeyS'});doc.dispatch('keydown',{code:'KeyW'});assert.equal(engine.state.player.crouching,false);engine.keys={};
engine.nodes=[];engine.water=[];engine.state.animals=[];engine.state.structures=[];engine.state.drops=[];engine.state.player.x=2000;engine.state.camera=1800;engine.state.dog.x=2025;engine.state.dog.mode='follow';
const dogEvent={clientX:225,clientY:context.PE.ground(2025)-15};
$('game-shell').dispatch('pointermove',{...dogEvent,target:$('game')});assert.ok($('world-tip').textContent.includes('Pet Kajo'));assert.ok($('world-tip').querySelector('.mouse-wheel-icon'));const petScroll=$('world-tip').firstElementChild;
$('game').dispatch('click',dogEvent);assert.equal(engine.action.target.type,'pet');engine.action=null;engine.state.dog.mode='follow';
let wheelPrevented=false;$('game').dispatch('wheel',{...dogEvent,deltaY:100,preventDefault(){wheelPrevented=true;}});assert.equal(wheelPrevented,true);assert.ok($('world-tip').textContent.includes('Throw a stick'));assert.notEqual($('world-tip').firstElementChild,petScroll,'each dog choice unfolds a new parchment');
$('game').dispatch('click',dogEvent);assert.equal(engine.state.dog.mode,'fetch');
engine.state.dog.mode='follow';engine.state.drops.push({id:'bird-ui',type:'carcass',species:'grouse',x:2200});context.performance={now:()=>performance.now()+200};
$('game').dispatch('wheel',{...dogEvent,deltaY:100});assert.ok($('world-tip').textContent.includes('Retrieve the bird'));$('game').dispatch('click',dogEvent);assert.equal(engine.state.dog.mode,'retrieve');
const drawCalls=[];assert.equal(context.PEIcons.draw(new Proxy({drawImage(...a){drawCalls.push(a);}},{get:(o,k)=>o[k]||(()=>{})}),'berries',0,0,96),true);assert.equal(drawCalls.length,1,'supplied icon images have loaded before play');
console.log('PASS Tab toggle/repeat, S toggle/W stand, dog hover/wheel/click commands and supplied-icon preload.');
click('#journal-button');advance();click('[data-panel="map"]');click('[data-travel="river"]');assert.equal(engine.transition,null);assert.ok(doc.querySelector('[role="alertdialog"]'));click('[data-travel-cancel]');assert.equal(engine.transition,null);click('[data-travel="river"]');doc.dispatch('keydown',{code:'Escape'});assert.equal(engine.transition,null);assert.equal(doc.querySelector('[role="alertdialog"]'),null);click('[data-travel="river"]');doc.dispatch('keydown',{code:'Tab'});assert.equal(doc.activeElement,doc.querySelector('[data-travel-confirm]'));click('[data-travel-confirm]');advance();
assert.equal(engine.transition.to,'river');click('#journal-button');assert.equal($('modal-backdrop').hidden,true,'Journal cannot freeze a travel fade');
for(let i=0;i<24;i++)engine.update(.05);assert.equal(engine.state.currentMap,'river');
click('#journal-button');advance();click('[data-panel="map"]');assert.ok(doc.querySelector('[data-travel="pond"]'));click('[data-travel="pond"]');assert.equal(engine.transition,null);assert.ok($('modal-content').textContent.includes('Sienilampi'));click('[data-travel-confirm]');advance();for(let i=0;i<24;i++)engine.update(.05);
assert.equal(engine.state.currentMap,'pond');assert.ok(engine.state.player.x>6000);
engine.state.player.x=context.PERegions.cabin.x;engine.state.camera=engine.state.player.x-340;engine.state.dog.x=engine.state.player.x+180;engine.action=null;
const hover=(dx,dy)=>{const p={clientX:340+dx*context.PERegions.cabin.scale,clientY:context.PE.ground(context.PERegions.cabin.x,'pond')+dy*context.PERegions.cabin.scale-context.PERegions.cabin.setback};$('game-shell').dispatch('pointermove',{...p,target:$('game')});return p;};
let repairClick=hover(0,-50);assert.ok($('world-tip').textContent.includes('Facade'));assert.ok(doc.querySelector('.repair-costs .missing')||$('world-tip').querySelector('.missing'));
hover(-90,-75);assert.ok($('world-tip').textContent.includes('Facade'));
hover(45,-70);assert.ok($('world-tip').textContent.includes('Facade'),'space between door and window selects facade');
hover(0,-170);assert.ok($('world-tip').textContent.includes('Roof'));hover(140,40);assert.ok($('world-tip').textContent.includes('Yard'));
for(const id of ['wood','firewood','cord','stone','fiber'])engine.state.inventory[id]=100;
repairClick=hover(0,-50);assert.equal($('world-tip').querySelector('.missing'),null);$('game').dispatch('click',repairClick);assert.equal(engine.action.target.part,'facade');
console.log('PASS real map-click travel/fade, pond right entrance, repair hit priorities and material tooltip states.');
engine.action=null;engine.state.cabinRepairs.facade=true;hover(0,-50);assert.equal($('world-tip').hidden,true,'restored facade has no hover label');hover(0,-170);assert.ok($('world-tip').textContent.includes('Roof'));
engine.state.cabinRepairs.roof=true;engine.state.cabinRepairs.yard=true;const doorClick=hover(0,-50);assert.ok($('world-tip').classList.contains('parchment-tip'));assert.ok($('world-tip').textContent.includes('Enter cabin'));$('game').dispatch('click',doorClick);assert.equal(engine.transition.room,true);engine.transition=null;hover(140,40);assert.equal($('world-tip').hidden,true,'restored yard does not block other clicks');
console.log('PASS restored hover suppression and unlocked cabin door mouse interaction.');
engine.action=null;engine.state.player.x=context.PERegions.pond.chair;engine.state.camera=engine.state.player.x-300;engine.state.dog.x=engine.state.player.x+100;const chairEvent={clientX:300,clientY:context.PE.ground(engine.state.player.x,'pond')-35};$('game-shell').dispatch('pointermove',{...chairEvent,target:$('game')});assert.ok($('world-tip').classList.contains('parchment-tip'));assert.ok($('world-tip').textContent.includes('Sit by the water'));$('game').dispatch('click',chairEvent);assert.equal(engine.state.player.sitting,true);
engine.action=null;engine.enterRegion('forest',1800);engine.state.camera=1500;engine.state.dog.x=2000;engine.state.structures=[];engine.nodes=[{id:'label-branch',type:'wood',x:1800},{id:'label-tree',type:'tree',x:1850}];
const point={clientX:300,clientY:context.PE.ground(1800)-10};
$('game-shell').dispatch('pointermove',{...point,target:$('game')});assert.ok($('world-tip').classList.contains('parchment-tip'));const firstScroll=$('world-tip').firstElementChild;
assert.equal(firstScroll.className,'field-scroll');assert.ok(firstScroll.textContent.includes('Dry branch'));assert.ok(firstScroll.textContent.includes('Click to gather'));
$('game-shell').dispatch('pointermove',{...point,target:$('game')});assert.equal($('world-tip').firstElementChild,firstScroll,'animation is not restarted for the same object');
$('game-shell').dispatch('pointerleave');$('game-shell').dispatch('pointermove',{...point,target:$('game')});assert.notEqual($('world-tip').firstElementChild,firstScroll,'returning to the object rolls it open again');
$('game-shell').dispatch('pointermove',{clientX:350,clientY:context.PE.ground(1850)-70,target:$('game')});assert.ok($('world-tip').textContent.includes('Click to fell'));
engine.state.drops=[{id:'label-carcass',type:'carcass',species:'rabbit',x:1770}];$('game-shell').dispatch('pointermove',{clientX:270,clientY:context.PE.ground(1770)-8,target:$('game')});assert.ok($('world-tip').textContent.includes('Click to skin'));
click('#journal-button');advance();click('[data-panel="map"]');assert.ok(doc.querySelector('[data-travel="forest"]').classList.contains('current'));assert.ok(doc.querySelector('[data-travel="pond"]').classList.contains('visited'));assert.ok(!doc.querySelector('[data-region="mountain"]').classList.contains('visited'));
console.log('PASS material parchment labels, per-target reveal lifecycle and current/visited map marker classes.');
engine.state.player.health=23;engine.state.player.hunger=0;engine.emit('change');assert.equal($('meter-health').getAttribute('aria-valuenow'),'23');assert.equal($('value-health').textContent,'23');assert.equal($('bar-health').style.width,'23%');assert.ok($('meter-health').parentElement.classList.contains('health-stat'));assert.ok($('meter-health').parentElement.classList.contains('health-danger'));assert.equal($('health-status').textContent,'Empty needs drain health');assert.equal($('stat-bars').children.at(-1),$('meter-health').parentElement);
context.L.set('fi');engine.emit('change');assert.equal($('meter-health').getAttribute('aria-label'),'TERVEYS');assert.equal($('health-status').textContent,'Tyhjät perustarpeet kuluttavat terveyttä');context.L.set('en');Object.assign(engine.state.player,{health:80,hunger:80});engine.emit('change');assert.equal($('health-status').textContent,'');assert.ok(!$('meter-health').parentElement.classList.contains('health-danger'));
console.log('PASS full-width health meter after needs, health warnings and bilingual accessible values.');
click('#close-modal');advance();engine.enterRegion('forest',1800);engine.state.camera=1500;engine.state.dog.x=2050;engine.nodes=[];engine.state.structures=[{id:'ui-camp',type:'fire',x:1800,lit:true,fuel:200}];
context.performance={now:()=>performance.now()+1000};const campPoint={clientX:300,clientY:context.PE.ground(1800)-10,target:$('game')};$('game-shell').dispatch('pointermove',campPoint);assert.ok($('world-tip').textContent.includes('Tend the campfire'));advance();$('game').dispatch('wheel',{...campPoint,deltaY:100});assert.ok($('world-tip').textContent.includes('Dismantle'));assert.ok($('world-tip').querySelector('.mouse-wheel-icon'));
$('game').dispatch('click',campPoint);assert.equal($('modal').dataset.panel,'dismantle');assert.equal(engine.state.structures.length,1);assert.equal(doc.activeElement,doc.querySelector('[data-cancel]'));assert.ok($('modal-content').textContent.includes('Are you sure'));click('[data-cancel]');advance();assert.equal(engine.pendingDismantle,null);assert.equal(engine.state.structures.length,1);
$('game').dispatch('click',campPoint);assert.equal($('modal').dataset.panel,'dismantle');doc.dispatch('keydown',{code:'Escape'});advance();assert.equal(engine.state.structures.length,1);assert.equal(engine.pendingDismantle,null);
$('game').dispatch('click',campPoint);click('[data-dismantle-confirm]');advance();assert.equal(engine.state.structures.length,0);assert.deepEqual(Array.from(engine.state.drops.filter(d=>d.id.startsWith('salvage-')),d=>[d.type,d.amount]),[['stone',2],['wood',2]]);
console.log('PASS structure wheel choice, safe focus, confirmation, Cancel/Escape and salvage after acceptance.');
engine.enterRegion('forest',context.PERegions.aarni.x);engine.state.camera=engine.npc.x-300;engine.state.dog.x=engine.npc.x+150;engine.action=null;
const aarniPoint={clientX:300,clientY:context.PE.ground(engine.npc.x)+engine.npc.depth-25,target:$('game')};$('game-shell').dispatch('pointermove',aarniPoint);assert.ok($('world-tip').textContent.includes('Aarni'));$('game').dispatch('click',aarniPoint);assert.equal($('modal').dataset.panel,'dialogue');
console.log('PASS setback trader door remains clickable at its visible position.');
click('#close-modal');advance();engine.enterRegion('pond',context.PERegions.cabin.x);engine.state.cabinRepairs={roof:true,facade:true,yard:true};context.PECabin.begin(engine,true);for(let i=0;i<22;i++)engine.update(.05);
assert.equal($('hud').hidden,false);assert.equal($('location-name').textContent,'Sienilampi · Home');assert.ok($('meter-health'));
const home=context.PECabin.home(engine),roomHover=(x,y)=>{const projected=context.PECabin.toScreen(engine,{x,y});const p={clientX:projected.x,clientY:projected.y,target:$('game')};$('game-shell').dispatch('pointermove',p);return p;};
home.x=877;engine.state.inventory.wood=9;$('game').dispatch('click',roomHover(880,400));assert.equal($('modal').dataset.panel,'home-chest');assert.ok($('modal-content').querySelector('.storage-columns'));click('[data-storage-card="wood"][data-direction="store"]');click('[data-storage-send]');assert.equal(home.storage.wood,9);click('[data-storage-card="wood"][data-direction="take"]');click('[data-storage-send]');assert.equal(engine.state.inventory.wood,9);click('#close-modal');advance();
home.x=320;engine.state.inventory.rawMeat=2;home.fire={lit:false,fuel:45};$('game').dispatch('click',roomHover(288,310));assert.equal($('modal').dataset.panel,'home-kitchen');assert.ok(!$('modal-content').querySelector('[data-home-action="wood"]'));assert.ok(!$('modal-content').querySelector('[data-home-action="relight"]'));assert.equal(doc.querySelector('[data-home-action="rawMeat"]').disabled,true);assert.ok($('modal-content').textContent.includes('Light the fireplace before cooking.'));click('#close-modal');advance();
home.x=465;$('game').dispatch('click',roomHover(465,310));assert.equal($('modal').dataset.panel,'home-hearth');assert.ok(!$('modal-content').querySelector('[data-home-action="rawMeat"]'));assert.ok(!$('modal-content').querySelector('[data-home-action="rawFish"]'));click('[data-home-action="wood"]');assert.equal(home.fire.lit,true);click('#close-modal');advance();
home.x=320;$('game').dispatch('click',roomHover(288,310));assert.equal($('modal').dataset.panel,'home-kitchen');const mealBefore=engine.state.inventory.cookedMeat;click('[data-home-action="rawMeat"]');assert.equal(engine.state.inventory.rawMeat,1);assert.equal(engine.state.inventory.cookedMeat,mealBefore+1);click('#close-modal');advance();
home.fire={lit:false,fuel:0};$('game').dispatch('click',roomHover(288,310));assert.equal(doc.querySelector('[data-home-action="rawMeat"]').disabled,true);click('#close-modal');advance();
home.x=719;engine.state.player.thirst=1;$('game').dispatch('click',roomHover(719,360));assert.equal(engine.state.player.thirst,100);assert.ok(sounds.includes('drink'));home.x=798;$('game').dispatch('click',roomHover(798,400));assert.equal(home.cupFull,true);assert.ok(sounds.includes('pour'));
home.x=886;$('game').dispatch('click',roomHover(885,290));assert.equal($('modal').dataset.panel,'home-bed');click('[data-home-action="sleep"]');advance();for(let i=0;i<22;i++)engine.update(.05);assert.equal(home.inside,true);
home.x=132;$('game').dispatch('click',roomHover(132,230));for(let i=0;i<22;i++)engine.update(.05);assert.equal(home.inside,false);
engine.state.inventory.canteen=1;engine.state.canteenFull=true;engine.state.player.thirst=5;click('[data-panel="inventory"]');advance();click('[data-tab="all"]');click('[data-select="canteen"]');assert.ok($('modal-content').textContent.includes('Full · one drink'));click('[data-use="canteen"]');assert.equal(engine.state.player.thirst,100);assert.equal(engine.state.canteenFull,false);assert.equal(doc.querySelector('[data-use="canteen"]').disabled,true);click('#close-modal');advance();
assert.ok($('title-card').textContent.includes('In Wildness is the preservation of the World.'));assert.ok(!$('title-card').textContent.includes('The trail disappears'));assert.ok(!$('title-card').querySelector('.menu-quote').textContent.includes('Walking'));assert.equal($('title-card').querySelector('.quote-author').textContent,'– Thoreau');
console.log('PASS indoor HUD, real chest/hearth/bed/mug/jug/exit clicks, sound events, canteen Journal use and title quote.');
engine.enterRegion('river',context.PERegions.trail.x);const cam=engine.state.camera,[bx,by,bw,bh]=context.PERegions.trailBox(cam);const branch={clientX:bx-cam+bw/2,clientY:by+bh/2,target:$('game')};$('game-shell').dispatch('pointermove',branch);assert.ok($('world-tip').textContent.includes('Sienilampi'));$('game').dispatch('click',branch);assert.equal(engine.transition.to,'pond');
for(const id of ['menu_banner','pick_banner1','pick_banner2','pick_banner3'])assert.ok(fs.existsSync(path.join(dir,'assets',id+'.png')));
const parchment=fs.readFileSync(path.join(dir,'parchment.css'),'utf8');assert.ok(parchment.includes('parchment-frames .18s steps(1,end)'));assert.ok(parchment.indexOf("0%{background-image:url('assets/pick_banner1.png')}")<parchment.indexOf("33.333%{background-image:url('assets/pick_banner2.png')}"));assert.ok(parchment.includes('66.667%,100%{background-image'));assert.ok(parchment.includes('prefers-reduced-motion'));assert.ok(parchment.includes('#title-card .menu-scroll:hover'));
console.log('PASS distant panorama travel hit test and supplied banner animation/preload wiring.');
engine.transition=null;engine.enterRegion('pond',5520);home.inside=true;home.x=640;engine.state.inventory.wood=11;home.storage.wood=0;engine.emit('panel',{panel:'home-chest'});
click('[data-storage-card="wood"][data-direction="store"]');click('[data-storage-portion="half"]');assert.ok($('storage-remaining').textContent.includes('6'));doc.querySelector('[data-storage-send]').dispatch('click');assert.equal(home.storage.wood,5);assert.equal(engine.state.inventory.wood,6);
const dt={setData(){},getData(){return 'forged';}},card=(id,dir)=>doc.querySelector('[data-storage-card="'+id+'"][data-direction="'+dir+'"]'),zone=side=>doc.querySelector('[data-storage-zone="'+side+'"]');
card('wood','take').dispatch('dragstart',{dataTransfer:dt,shiftKey:true});zone('pack').dispatch('dragover',{dataTransfer:dt});assert.ok(zone('pack').classList.contains('drag-over'));zone('pack').dispatch('drop',{dataTransfer:dt});assert.equal(home.storage.wood,3);assert.equal(engine.state.inventory.wood,8);
zone('pack').dispatch('drop',{dataTransfer:dt});assert.equal(engine.state.inventory.wood,8,'repeated or foreign drops cannot duplicate items');
card('wood','store').dispatch('dragstart',{dataTransfer:dt});zone('pack').dispatch('drop',{dataTransfer:dt});assert.equal(engine.state.inventory.wood,8,'same-source drop leaves stack unchanged');
click('[data-storage-card="wood"][data-direction="store"]');$('storage-amount').value='2';$('storage-amount').dispatch('input');assert.equal(doc.querySelector('[data-storage-send]').disabled,false);card('wood','store').dispatch('dragstart',{dataTransfer:dt});zone('chest').dispatch('drop',{dataTransfer:dt});assert.equal(engine.state.inventory.wood,6);assert.equal(home.storage.wood,5);
click('[data-storage-card="wood"][data-direction="store"]');$('storage-amount').value='1.5';$('storage-amount').dispatch('input');assert.equal(doc.querySelector('[data-storage-send]').disabled,true);doc.querySelector('[data-storage-send]').dispatch('click');assert.equal(home.storage.wood,5);
$('storage-amount').value='2';$('storage-amount').dispatch('input');card('wood','store').dispatch('dragstart',{dataTransfer:dt});engine.state.inventory.wood--;zone('chest').dispatch('drop',{dataTransfer:dt});assert.equal(home.storage.wood,5,'changed source invalidates drag');
card('wood','take').dispatch('dragstart',{dataTransfer:dt});click('#close-modal');advance();zone('pack').dispatch('drop',{dataTransfer:dt});assert.equal(home.storage.wood,5,'closing chest cancels pending drag');
engine.emit('panel',{panel:'home-chest'});context.L.set('fi');click('[data-storage-card="wood"][data-direction="take"]');assert.ok($('modal-content').textContent.includes('Puolita pino'));context.L.set('en');click('#close-modal');advance();
console.log('PASS chest grid, half/exact split, two-way drag/drop, malformed/foreign/stale/cancelled transfers and Finnish labels.');
})().catch(e=>{console.error(e);process.exitCode=1;});
